Add logging to scala worker
lucidsoftware/rules_scala pull request #10
Opened 2021-04-09 22:47 UTC by yyuan-lucid

2021-04-09 23:17 UTC, JaredNeil requested changes

2021-04-09 23:17 UTC, JaredNeil commented on src/main/scala/higherkindness/rules_scala/common/worker/WorkerMain.scala
> +            System.out.println(s"A WorkRequest $requestId is received. Args: $args")
```suggestion
            System.out.println(s"WorkRequest $requestId received with args: $args")
```

2021-04-09 23:17 UTC, JaredNeil commented on src/main/scala/higherkindness/rules_scala/common/worker/WorkerMain.scala
> +                System.out.println(s"Work future successfully completed. A WorkResponse $requestId was sent.")
```suggestion
                System.out.println(s"WorkResponse $requestId sent with code $code")
```

2021-04-09 23:17 UTC, JaredNeil commented on src/main/scala/higherkindness/rules_scala/common/worker/WorkerMain.scala
> +                System.err.println(s"Work future failed. A WorkResponse $requestId was sent.")
```suggestion
                System.err.println(s"Uncaught exception in Future while proccessing WorkRequest $requestId:")
                e.printStackTrace(System.err)
```

2021-04-09 23:56 UTC, JaredNeil approved these changes

2021-04-09 23:57 UTC, JaredNeil commented
Were you able to test this and see the logs?

2021-04-10 00:25 UTC, yyuan-lucid commented
Yup. Also confirmed the NullPointerException went away with the fix.
![image](https://user-images.githubusercontent.com/81650633/114252122-fa4a1000-9960-11eb-92a5-61b6432fcf5f.png)

2021-04-12 16:01 UTC, JaredNeil commented
Oh, can you print the actual strings in `args`?

2021-04-12 16:26 UTC, yyuan-lucid commented
![image](https://user-images.githubusercontent.com/81650633/114428552-92badd00-9b79-11eb-86eb-221ea9769566.png)

2021-04-12 16:32 UTC, merged