Make Stamps deterministic
lucidsoftware/rules_scala pull request #42
Opened 2024-03-15 17:59 UTC by jjudd

2024-03-27 22:55 UTC, JaredNeil requested changes
Do you have any performance numbers on this change? I know there was a different change that made things much slower at some point, but I don't remember if it was similar to this in any way.

2024-03-27 22:55 UTC, JaredNeil commented on src/main/scala/higherkindness/rules_scala/workers/zinc/compile/AnalysisStore.scala
> +    TreeMap[String, Schema.Stamps.StampType]() ++ stampTypeMap.asScala
```suggestion
    TreeMap.from(stampTypeMap.asScala)
```
Though going from a Java type to a Scala type just to put it ordered map and then convert back to a Java type seems wasteful. Why not go directly to the ordered Java map?

2024-03-29 01:21 UTC, jjudd commented on src/main/scala/higherkindness/rules_scala/workers/zinc/compile/AnalysisStore.scala
> +    TreeMap[String, Schema.Stamps.StampType]() ++ stampTypeMap.asScala
Good questions, I don't remember this code was written so long ago. Lemme go take another look. I bet we can go directly to the ordered Java map and that was a rough edge I forgot about last year.

2024-03-29 01:23 UTC, jjudd commented
The performance regression last year wasn't caused by the sorting to make things deterministic. It was caused by a change I made in the worker that worked around the Scala 2 tasty classloader caching bug before I knew that bug existed. I don't remember exactly the details of that regression as it's been too long, but I know it wasn't related to the sorting changes like these.

2024-03-29 01:53 UTC, jjudd commented on src/main/scala/higherkindness/rules_scala/workers/zinc/compile/AnalysisStore.scala
> +    TreeMap[String, Schema.Stamps.StampType]() ++ stampTypeMap.asScala
I updated this to use a `java.util.TreeMap` directly.

2024-03-29 17:43 UTC, JaredNeil approved these changes
Sure would be nice if they just used `TreeMap` internally from the beginning.

2024-04-10 04:14 UTC, merged